### ISSUE TITLE
handlers inexistant for EGOImageLoadConnection

### ISSUE THREAD

**Issue by pomarec** [enormego/EGOImageLoading#10]
When using blocks, app crashes when trying to use :
    - (void)loadImageForURL:(NSURL_)aURL completion:(void (^)(UIImage_ image, NSURL\* imageURL, NSError\* error))completion;

```
 -[EGOImageLoadConnection handlers]: unrecognized selector sent to instance 0x5d58e00
```

I fixed importing EGOImageLoader.h in EGOImageLoadConnection.h

**Comment by devindoty** [comment]
Can you post a snippet of the code you're using to call loadImageForURL:completion:

**Comment by pomarec** [comment]
I put this in EGOImageLoader:

```
- (void)loadImagesForURLs:(NSSet*)someUrls completion:(void (^)(void))completion {
    NSMutableSet *urlsToDownload = [NSMutableSet setWithSet:someUrls];
    for (NSURL *url in someUrls) {
        [self loadImageForURL:url completion:^(UIImage *image, NSURL *imageURL, NSError *error) {
            [urlsToDownload removeObject:imageURL];
            if (urlsToDownload.count == 0)
                completion();
        }];
    }
}
```

And called it this way : 

```
NSMutableSet *set = [NSMutableSet set];
[set addObject:[NSURL URLWithString:@"http://myurl0"]];
[set addObject:[NSURL URLWithString:@"http://myurl1"]];
[set addObject:[NSURL URLWithString:@"http://myurl2"]];
[[EGOImageLoader sharedImageLoader] loadImagesForURLs:set completion:^(void) {
    NSLog(@"Downloads completed);
}];
```

**Comment by devindoty** [comment]
When you enter the loadImageForURL:completion: block, urlsToDownload is frozen by the block. You can fix this by prefixing with __block, this allows variables to be mutable in the local scope. Your NSMutableSet declaration should look like the one below.

 __block NSMutableSet *urlsToDownload = [NSMutableSet setWithSet:someUrls];

http://developer.apple.com/library/ios/#DOCUMENTATION/Cocoa/Conceptual/Blocks/Articles/bxVariables.html

**Comment by pomarec** [comment]
I'm not sure but I don't think is related to this.
As I understand the issue, if you don't EGOImageLoader.h in EGOImageLoadConnection.h, __EGOIL_USE_BLOCKS is not set to 1 and 'handler' property of EGOImageLoadConnection is not defined. What do you think about it ?

**Comment by intabulas** [comment]
Issue is that the __EGOIL_USE_BLOCKS define in EGOImageLoader isnt visible to EGOImageLoadConnection   

Quick hack to get it to work is to simply define it the preprocessor macros in the build settings
