### ISSUE TITLE
Delayed Loading Behavior in UITableView

### ISSUE THREAD

**Issue by bluesuedesw** [enormego/EGOImageLoading#18]
First off, thanks so much for making this great resource available.

So I'm loading my remote EGOImageView images in a UITableView with custom cells, if the user is currently scrolling, the images will not display until the scrolling motion comes to a complete stop. It looks as though the images are already downloaded however something is blocking them from displaying until the scrolling ends. I'd like to not have this behavior and just load the images in once ready if it is not too much of a performance hit... 

I can't seem to spot where/why this is happening in the code. Can anyone enlighten me on this? 

One thing I did try is to delay the _connection and schedule it to start on the main runloop in EGOImageLoadConnection.m start as per:

http://www.cocoanetics.com/2011/05/and-now-lazy-loading-with-nsurlconnection/

However I still get the delayed image loading.

**Comment by devindoty** [comment]
You would want to change NSRunLoopCommonModes to NSDefaultRunLoopMode in EGOHTTPRequests startConnectionInBackgroundWithRequest: method.

**Comment by bluesuedesw** [comment]
Where do I find the startConnectionInBackgroundWithRequest: method ? 

I tried altering the start: method in EGOImaeLoadConnection.m to: to use the NSDefaultRunLoopMode without success...

```
    _connection = [[NSURLConnection alloc] initWithRequest:request delegate:self startImmediately:NO];

    // Added so scrollview does not block image loading on completion, change startsImmediately to NO
    [_connection scheduleInRunLoop:[NSRunLoop currentRunLoop] forMode:NSDefaultRunLoopMode];
    [_connection start];

```

**Comment by devindoty** [comment]
Ah, I didn't realize it's not running on EGOHTTPRequest anymore. The problem is the callback then, all of the completion(...) blocks should be wrapped in a dispatch queue on the main thread. The only area I don't see that happening is if the image is cached. 

loadImageForURL: should look like this in the has cache case. 

if(anImage) {
    dispatch_async(kCompletionsQueue, ^{
        completion(anImage, aURL, nil);
         }
}

**Comment by bluesuedesw** [comment]
Thanks for the quick help, though I'm still experiencing the delayed image display with your recommendation. 

Perhaps I'm not being clear enough... The connections start/load fine, its just that the EGOImageView's in my cells won't actually draw the image until the table view scrolling stops or the user takes their finger off the screen.

**Comment by devindoty** [comment]
A few changes made, but here's a demo of it throwing the images up while dragging in a table view. 

http://cld.devin.me/CZiX

Mainly the call to start from EGOImageLoader, it's being called on a background thread using performSelector, that won't get called until a user is done dragging.

**Comment by bluesuedesw** [comment]
Impressive, you got it. Thanks so much for your assistance with this issue. 

Unfortunately in my app this mod does cause a pretty big performance hit making the tableview pretty jerky as the cells scroll on by. I guess that's the tradeoff for delaying the image drawing. However, I have used plenty of apps that handle remote image loading and scrolling with ease so perhaps there is another solution out there.

**Comment by devindoty** [comment]
Yep, that's something that comes with this type of implementation. It really needs to be tailored your apps specific use case, but you can get 60fps with a bit of work
