### ISSUE TITLE
EGOCache.h Missing

### ISSUE THREAD

**Issue by adjohn** [enormego/EGOImageLoading#2]
When compiling the Demo project, it seems that the EGOCache files are missing, there is just an empty directory.

**Comment by maintainer** [comment]
You can take EGOCache here: http://github.com/lukeredpath/EGOCache

**Comment by enormego** [comment]
EGOCache is linked as a git submodule, you'll need to run these too:

git submodule init
git submodule update

I'll update the README accordingly.
