### ISSUE TITLE
Can't round corners with imageview.layer.cornerRadius

### ISSUE THREAD

**Issue by sabernar** [enormego/EGOImageLoading#3]
With a UIImageView,  you can do this:

image.layer.cornerRadius

but EGOImageView does not allow you to use the Quartz corner rounding.

**Comment by dnstevenson** [comment]
I had the same issue, but got it to work. I did the following:

1) For newly pulled images, simply add a delegate that does the work of rounding the corners after - (void)imageViewLoadedImage:(EGOImageView*)inImageView is called

2) For existing images, I modified the EGOImageView.m file to add a delegate callback inside setImageURL after self.image = anImage.  Like this snippet:

```
if(anImage) {
    self.image = anImage;
```

// new callback
        if([self.delegate respondsToSelector:@selector(imageViewLoadedImage:)]) {
            [self.delegate imageViewLoadedImage:self];
        }  
    } else {
        self.image = self.placeholderImage;
    }

**Comment by shnhrrsn** [comment]
If you set masksToBounds to YES, it will work:
        imageView.layer.cornerRadius = 4.0f;
        imageView.layer.masksToBounds = YES;

**Comment by ghost** [comment]
It works for me
