### ISSUE TITLE
Handle redirection response-

### ISSUE THREAD

**Issue by huntrax11** [enormego/EGOImageLoading#7]
I'm making an app with EGOImageLoading class, and there are some difficulty to handle twitter profile image.
As you see this profile picture image url ( http://api.twitter.com/1/users/profile_image/43491292?size=normal ),
some image url is served with redirection response.
Would you handle redirection response ?
Thanks.

**Comment by shnhrrsn** [comment]
Hmm, are you sure EGOImageLoader is the cause of the error?  I just dropped that URL into the demo app and it loaded fine.  Could you post some sample code that demonstrates the problem?

**Comment by huntrax11** [comment]
Ahh,, It seems my problem thanks for quick response.
