### ISSUE TITLE
No EGOCache files on repository

### ISSUE THREAD

**Issue by martindibella** [enormego/EGOImageLoading#9]
Hey guys,
I've just cloned the repo, opened the xCode demo project and found that the files EGOCache.h and .m are not in the EGOCache directory.

**Comment by diwu** [comment]
EGOCache is another stand-alone project. You need to clone that project separately from GitHub. Here's the link, https://github.com/enormego/EGOCache .

**Comment by martindibella** [comment]
Sorry about that! I think a comment on the project regarding the dependency on EGOCache would be great.
